# Dependabot configuration file
# See: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Limit the number of open PRs to avoid overwhelming maintainers
    open-pull-requests-limit: 25
    # Assign labels to PRs
    labels:
      - "dependencies"
    # Specify reviewers for PRs
    reviewers:
      - "mantejsingh"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Assign labels to PRs
    labels:
      - "dependencies"
      - "github-actions"
    # Allow up to 3 PRs to be opened at once
    open-pull-requests-limit: 3 