name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only run for PRs created by dependabot
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - name: Auto-merge for Dependabot PRs
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          echo "Processing PR #$PR_NUMBER: $TITLE"
          
          # Approve the PR
          gh pr review "$PR_NUMBER" --approve
          
          # Enable auto-merge (squash)
          gh pr merge "$PR_NUMBER" --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 