name: PR Size Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Size Label
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "XS": "< 10",
              "S": "10-99",
              "M": "100-299",
              "L": "300-499",
              "XL": "500-999",
              "XXL": "1000+"
            } 